name: "test-dev"

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: tsc, build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: action/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v3
        id: Cache
        with:
          path: node_modules
          key: npm_packages-${{hashFiles('**/package-lock.json')}}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Run build
        if: ${{always()}}
        run: npm run build
